# Generated by Django 5.0.3 on 2026-07-01 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=120, verbose_name="牌面文字")),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("orthodox", "正字"),
                            ("loan", "借字"),
                            ("popular", "俗写"),
                            ("phonetic", "拟音"),
                            ("romanization", "罗马字"),
                            ("uncertain", "不确定"),
                        ],
                        default="uncertain",
                        max_length=20,
                        verbose_name="包装类型",
                    ),
                ),
                (
                    "unicode",
                    models.CharField(blank=True, max_length=80, verbose_name="Unicode"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "包装",
                "verbose_name_plural": "包装",
                "ordering": ["text", "package_type"],
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "shelf_type",
                    models.CharField(
                        choices=[
                            ("official", "官方推荐"),
                            ("user", "用户自建"),
                            ("campaign", "征集活动"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "货架",
                "verbose_name_plural": "货架",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Dialect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                (
                    "code",
                    models.SlugField(max_length=120, unique=True, verbose_name="代码"),
                ),
                (
                    "region_level",
                    models.CharField(
                        choices=[
                            ("family", "方言族"),
                            ("dialect", "方言"),
                            ("area", "片区"),
                            ("county", "县区"),
                            ("town", "乡镇"),
                            ("community", "社区"),
                        ],
                        default="dialect",
                        max_length=20,
                        verbose_name="层级",
                    ),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=80, verbose_name="省"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="市"),
                ),
                (
                    "county",
                    models.CharField(blank=True, max_length=80, verbose_name="县区"),
                ),
                (
                    "town",
                    models.CharField(blank=True, max_length=80, verbose_name="乡镇"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="guantou.dialect",
                        verbose_name="父级方言点",
                    ),
                ),
            ],
            options={
                "verbose_name": "方言点",
                "verbose_name_plural": "方言点",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="风味名")),
                ("definition", models.TextField(verbose_name="释义")),
                (
                    "mandarin",
                    models.JSONField(
                        blank=True, default=list, verbose_name="普通话概念"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "geo_scope",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="地理范围"
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(default=True, verbose_name="是否可见"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flavors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "风味",
                "verbose_name_plural": "风味",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="FlavorPackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("primary", "主写法"),
                            ("synonym", "同义写法"),
                            ("borrowed", "假借"),
                            ("disputed", "争议"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="映射类型",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=240, verbose_name="说明"),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guantou.flavor"
                    ),
                ),
            ],
            options={
                "verbose_name": "风味包装关系",
                "verbose_name_plural": "风味包装关系",
            },
        ),
        migrations.CreateModel(
            name="FlavorVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipa",
                    models.CharField(blank=True, max_length=120, verbose_name="IPA"),
                ),
                (
                    "romanization",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="拼音/罗马字"
                    ),
                ),
                (
                    "tone_value",
                    models.CharField(blank=True, max_length=40, verbose_name="调值"),
                ),
                (
                    "reading_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="读音类型"
                    ),
                ),
                (
                    "sandhi_info",
                    models.JSONField(blank=True, default=dict, verbose_name="变调信息"),
                ),
                (
                    "is_canonical",
                    models.BooleanField(default=False, verbose_name="是否认证主变体"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("verified", "已认证"),
                            ("rejected", "已驳回"),
                            ("disputed", "争议"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("audio_url", models.URLField(blank=True, verbose_name="音频")),
                (
                    "audio_source",
                    models.CharField(
                        choices=[
                            ("user", "用户上传"),
                            ("tts", "TTS"),
                            ("import", "导入"),
                            ("none", "无"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="音频来源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flavor_variants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "dialect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flavor_variants",
                        to="guantou.dialect",
                        verbose_name="方言点",
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="guantou.flavor",
                        verbose_name="风味",
                    ),
                ),
            ],
            options={
                "verbose_name": "味觉变体",
                "verbose_name_plural": "味觉变体",
                "ordering": ["flavor_id", "-is_canonical", "id"],
            },
        ),
        migrations.CreateModel(
            name="Can",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_url", models.URLField(verbose_name="音频")),
                (
                    "concept_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="普通话概念"
                    ),
                ),
                (
                    "source_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="来源说明"
                    ),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=80, verbose_name="省"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="市"),
                ),
                (
                    "county",
                    models.CharField(blank=True, max_length=80, verbose_name="县区"),
                ),
                (
                    "town",
                    models.CharField(blank=True, max_length=80, verbose_name="乡镇"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="时长毫秒"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unlabeled", "无标"),
                            ("pending", "待校验"),
                            ("tentative", "社区暂定"),
                            ("verified", "正品认证"),
                            ("disputed", "争议"),
                            ("rejected", "已驳回"),
                        ],
                        default="unlabeled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(default=False, verbose_name="是否可见"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="访问量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="录制者",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_cans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "dialect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cans",
                        to="guantou.dialect",
                        verbose_name="方言点",
                    ),
                ),
                (
                    "flavor_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cans",
                        to="guantou.flavorvariant",
                        verbose_name="味觉变体",
                    ),
                ),
            ],
            options={
                "verbose_name": "罐头",
                "verbose_name_plural": "罐头",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Nameplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_content",
                    models.CharField(max_length=160, verbose_name="牌面文字"),
                ),
                ("definition", models.TextField(blank=True, verbose_name="释义")),
                (
                    "evidence_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "本人记忆"),
                            (2, "社区公认"),
                            (3, "文献考据"),
                            (4, "官方认证"),
                        ],
                        default=1,
                        verbose_name="证据等级",
                    ),
                ),
                (
                    "source_citation",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="证据来源"
                    ),
                ),
                ("weight", models.IntegerField(default=0, verbose_name="权重")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="是否主铭牌"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "can",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nameplates",
                        to="guantou.can",
                        verbose_name="罐头",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nameplates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="贴牌者",
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nameplates",
                        to="guantou.flavor",
                        verbose_name="风味",
                    ),
                ),
            ],
            options={
                "verbose_name": "铭牌",
                "verbose_name_plural": "铭牌",
                "ordering": ["can_id", "-is_primary", "-weight", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                fields=("text", "package_type"), name="unique_package_text_type"
            ),
        ),
        migrations.AddField(
            model_name="nameplate",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nameplates",
                to="guantou.package",
                verbose_name="包装",
            ),
        ),
        migrations.AddField(
            model_name="flavorpackage",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="guantou.package"
            ),
        ),
        migrations.AddField(
            model_name="flavor",
            name="packages",
            field=models.ManyToManyField(
                blank=True,
                related_name="flavors",
                through="guantou.FlavorPackage",
                to="guantou.package",
                verbose_name="包装",
            ),
        ),
        migrations.AddField(
            model_name="shelf",
            name="cans",
            field=models.ManyToManyField(
                blank=True, related_name="shelves", to="guantou.can"
            ),
        ),
        migrations.AddField(
            model_name="shelf",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shelves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="shelf",
            name="flavors",
            field=models.ManyToManyField(
                blank=True, related_name="shelves", to="guantou.flavor"
            ),
        ),
        migrations.AddConstraint(
            model_name="flavorpackage",
            constraint=models.UniqueConstraint(
                fields=("flavor", "package"), name="unique_flavor_package"
            ),
        ),
    ]
