# Generated by Django 5.0.3 on 2026-08-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0002_nameplatesupport"),
    ]

    operations = [
        migrations.AddField(
            model_name="can",
            name="transition_log",
            field=models.JSONField(
                blank=True, default=list, verbose_name="状态转换日志"
            ),
        ),
    ]
