# Generated by Django 5.1.5 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guantou", "0006_can_social"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=20, unique=True)),
                ("count", models.PositiveBigIntegerField(default=0)),
                ("last_searched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-count", "-last_searched_at", "id"]},
        ),
        migrations.CreateModel(
            name="SearchTermHit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributer", models.CharField(max_length=80)),
                ("hit_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="guantou.searchterm",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="searchtermhit",
            constraint=models.UniqueConstraint(
                fields=("term", "attributer", "hit_date"),
                name="unique_daily_search_term_hit",
            ),
        ),
    ]
