# Generated by Django 6.0.7 on 2026-08-10 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_dialect_circles(apps, schema_editor):
    Dialect = apps.get_model("guantou", "Dialect")
    DialectCircle = apps.get_model("guantou", "DialectCircle")
    DialectCircle.objects.bulk_create(
        [
            DialectCircle(
                dialect=dialect,
                name=f"{dialect.name}圈",
                description=dialect.description
                or f"一起听、录和校验{dialect.name}乡音。",
            )
            for dialect in Dialect.objects.all()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0008_cancommentlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DialectCircle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="圈子名称")),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否开放"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dialect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="circle",
                        to="guantou.dialect",
                        verbose_name="主方言",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dialect_circles",
                        through="guantou.CircleMembership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "方言圈",
                "verbose_name_plural": "方言圈",
                "ordering": ["dialect__sort_order", "id"],
            },
        ),
        migrations.RunPython(create_dialect_circles, migrations.RunPython.noop),
        migrations.AddField(
            model_name="circlemembership",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="guantou.dialectcircle",
            ),
        ),
        migrations.CreateModel(
            name="RecordingChallenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                ("prompt", models.CharField(max_length=300, verbose_name="录音提示")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dialect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recording_challenges",
                        to="guantou.dialect",
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recording_challenges",
                        to="guantou.flavor",
                    ),
                ),
            ],
            options={
                "verbose_name": "录音挑战",
                "verbose_name_plural": "录音挑战",
                "ordering": ["sort_order", "-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="circlemembership",
            constraint=models.UniqueConstraint(
                fields=("circle", "user"), name="unique_circle_membership"
            ),
        ),
    ]
