# Generated by Django 6.0.7 on 2026-08-12 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0014_repair_legacy_schema_drift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanTransition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("unlabeled", "无标"),
                            ("pending", "待校验"),
                            ("tentative", "社区暂定"),
                            ("verified", "正品认证"),
                            ("disputed", "争议"),
                            ("rejected", "已驳回"),
                        ],
                        max_length=20,
                        verbose_name="转换前状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("unlabeled", "无标"),
                            ("pending", "待校验"),
                            ("tentative", "社区暂定"),
                            ("verified", "正品认证"),
                            ("disputed", "争议"),
                            ("rejected", "已驳回"),
                        ],
                        max_length=20,
                        verbose_name="转换后状态",
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="操作")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=300, verbose_name="原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发生时间"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="can_transitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "can",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="guantou.can",
                        verbose_name="罐头",
                    ),
                ),
            ],
            options={
                "verbose_name": "罐头状态转换",
                "verbose_name_plural": "罐头状态转换",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["can", "created_at"], name="can_transition_can_at_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="can_transition_actor_at_idx",
                    ),
                    models.Index(
                        fields=["from_status", "to_status", "created_at"],
                        name="can_transition_status_at_idx",
                    ),
                ],
            },
        ),
    ]
