# Generated by Django 6.0.7 on 2026-08-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0015_cancomment_nameplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCanSelection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="选择时间"),
                ),
                (
                    "can",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_selections",
                        to="guantou.can",
                        verbose_name="当日罐头",
                    ),
                ),
            ],
            options={
                "verbose_name": "今日罐选择",
                "verbose_name_plural": "今日罐选择",
                "ordering": ["-date"],
            },
        ),
    ]
