# Generated by Django 6.1 on 2026-09-04 18:08

import django.db.models.deletion
import django.utils.timezone
import guantou.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0019_cancomment_parent_cancomment_reply_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="概念代码"
                    ),
                ),
                ("label", models.CharField(max_length=160, verbose_name="显示名称")),
                ("definition", models.TextField(blank=True, verbose_name="定义")),
                (
                    "external_refs",
                    models.JSONField(blank=True, default=dict, verbose_name="外部引用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "抽象概念",
                "verbose_name_plural": "抽象概念",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="词条大意")),
                (
                    "identity_note",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        verbose_name="读音或核心意义辨识说明",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "初稿"),
                            ("reviewed", "已整理"),
                            ("disputed", "有分歧"),
                            ("redirected", "已合并跳转"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(default=True, verbose_name="是否可见"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "canonical_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redirected_entries",
                        to="guantou.entry",
                        verbose_name="合并后的规范词条",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "usage_dialect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="guantou.dialect",
                        verbose_name="已知使用范围",
                    ),
                ),
            ],
            options={
                "verbose_name": "词条",
                "verbose_name_plural": "词条",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EntrySense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sense_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="义项编号"
                    ),
                ),
                ("gloss", models.TextField(verbose_name="释义")),
                ("usage_note", models.TextField(blank=True, verbose_name="用法说明")),
                (
                    "examples",
                    models.JSONField(blank=True, default=list, verbose_name="例句"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "初稿"),
                            ("reviewed", "已整理"),
                            ("disputed", "有分歧"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_entry_senses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senses",
                        to="guantou.entry",
                        verbose_name="词条",
                    ),
                ),
            ],
            options={
                "verbose_name": "词条义项",
                "verbose_name_plural": "词条义项",
                "ordering": ["entry_id", "sense_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="EntrySenseConcept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("exact", "对应"),
                            ("broader", "较宽"),
                            ("narrower", "较窄"),
                            ("related", "相关"),
                        ],
                        default="exact",
                        max_length=20,
                        verbose_name="关系",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sense_links",
                        to="guantou.concept",
                        verbose_name="抽象概念",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sense_concepts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "sense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_links",
                        to="guantou.entrysense",
                        verbose_name="词条义项",
                    ),
                ),
            ],
            options={
                "verbose_name": "义项概念关系",
                "verbose_name_plural": "义项概念关系",
                "ordering": ["sense_id", "concept_id", "id"],
            },
        ),
        migrations.AddField(
            model_name="entrysense",
            name="concepts",
            field=models.ManyToManyField(
                blank=True,
                related_name="senses",
                through="guantou.EntrySenseConcept",
                to="guantou.concept",
                verbose_name="抽象概念",
            ),
        ),
        migrations.CreateModel(
            name="EvidenceRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("user_statement", "用户原话"),
                            ("oral", "口述"),
                            ("fieldwork", "田野记录"),
                            ("book", "书籍"),
                            ("article", "论文或文章"),
                            ("archive", "档案"),
                            ("web", "网页"),
                            ("legacy", "旧库原文"),
                            ("other", "其他"),
                        ],
                        max_length=24,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "original_text",
                    models.TextField(blank=True, verbose_name="来源原文"),
                ),
                (
                    "original_writing",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="原样写法"
                    ),
                ),
                (
                    "original_gloss",
                    models.TextField(blank=True, verbose_name="原样释义"),
                ),
                (
                    "original_pronunciation",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="原样读音"
                    ),
                ),
                (
                    "citation",
                    models.CharField(blank=True, max_length=500, verbose_name="出处"),
                ),
                (
                    "source_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="来源快照"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收录时间"),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="贡献者",
                    ),
                ),
            ],
            options={
                "verbose_name": "证据记录",
                "verbose_name_plural": "证据记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PronunciationVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipa",
                    models.CharField(blank=True, max_length=160, verbose_name="IPA"),
                ),
                (
                    "base_romanization",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="变调前罗马字"
                    ),
                ),
                (
                    "surface_romanization",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="变调后罗马字"
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("general", "通用"),
                            ("literary", "文读"),
                            ("colloquial", "白读"),
                            ("other", "其他"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="读音类型",
                    ),
                ),
                ("usage_note", models.TextField(blank=True, verbose_name="用法说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "初稿"),
                            ("reviewed", "已整理"),
                            ("disputed", "有分歧"),
                            ("rejected", "不采用"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pronunciation_variants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "dialect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_pronunciations",
                        to="guantou.dialect",
                        verbose_name="方言范围",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_variants",
                        to="guantou.entry",
                        verbose_name="词条",
                    ),
                ),
            ],
            options={
                "verbose_name": "地区读音",
                "verbose_name_plural": "地区读音",
                "ordering": ["entry_id", "dialect_id", "reading_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_url", models.URLField(verbose_name="音频")),
                (
                    "recording_type",
                    models.CharField(
                        choices=[
                            ("word", "词"),
                            ("phrase", "短语"),
                            ("example", "例句"),
                            ("other", "其他"),
                        ],
                        default="word",
                        max_length=20,
                        verbose_name="录音类型",
                    ),
                ),
                (
                    "original_gloss",
                    models.TextField(blank=True, verbose_name="贡献者原始大意"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="时长毫秒"),
                ),
                (
                    "rights_statement",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="录音授权说明"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "初稿"),
                            ("published", "已公开"),
                            ("disputed", "有分歧"),
                            ("rejected", "不采用"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(default=False, verbose_name="是否可见"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="非定位扩展信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="录制者",
                    ),
                ),
                (
                    "usage_dialect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recordings",
                        to="guantou.dialect",
                        verbose_name="使用地区",
                    ),
                ),
            ],
            options={
                "verbose_name": "录音",
                "verbose_name_plural": "录音",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RecordingEntryLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "主要词条"),
                            ("mention", "句中词"),
                            ("competing", "竞争解释"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="关系角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "待确认"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("disputed", "有分歧"),
                        ],
                        default="suggested",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="是否为当前关系"),
                ),
                (
                    "review_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="确认理由"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recording_entry_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提议者",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recording_links",
                        to="guantou.entry",
                        verbose_name="词条",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_links",
                        to="guantou.recording",
                        verbose_name="录音",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recording_entry_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认者",
                    ),
                ),
                (
                    "sense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recording_links",
                        to="guantou.entrysense",
                        verbose_name="对应义项",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successors",
                        to="guantou.recordingentrylink",
                        verbose_name="修订自",
                    ),
                ),
            ],
            options={
                "verbose_name": "录音词条关系",
                "verbose_name_plural": "录音词条关系",
                "ordering": ["recording_id", "role", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("submitted", "原始提交"),
                            ("supports", "支持"),
                            ("disputes", "质疑"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="证据关系",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关联时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_evidence_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联者",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="guantou.entry",
                    ),
                ),
                (
                    "sense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="guantou.entrysense",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim_links",
                        to="guantou.evidencerecord",
                        verbose_name="证据",
                    ),
                ),
                (
                    "pronunciation_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="guantou.pronunciationvariant",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="guantou.recording",
                    ),
                ),
                (
                    "recording_entry_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="guantou.recordingentrylink",
                    ),
                ),
            ],
            options={
                "verbose_name": "证据关联",
                "verbose_name_plural": "证据关联",
                "ordering": ["evidence_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="UsageAttestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="补充说明"
                    ),
                ),
                (
                    "attested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="确认时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "attester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_attestations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认者",
                    ),
                ),
                (
                    "dialect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_attestations",
                        to="guantou.dialect",
                        verbose_name="确认范围",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_attestations",
                        to="guantou.entry",
                        verbose_name="词条",
                    ),
                ),
            ],
            options={
                "verbose_name": "本地使用确认",
                "verbose_name_plural": "本地使用确认",
                "ordering": ["-attested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WritingForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=160, verbose_name="写法")),
                (
                    "normalized_text",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="检索归一写法"
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("orthographic", "汉字正字"),
                            ("popular", "俗写"),
                            ("loan", "借字"),
                            ("phonetic", "拟音"),
                            ("romanization", "罗马字"),
                            ("uncertain", "待考写法"),
                        ],
                        default="uncertain",
                        max_length=20,
                        verbose_name="写法类型",
                    ),
                ),
                (
                    "language_tag",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="语言标签"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "词条写法",
                "verbose_name_plural": "词条写法",
                "ordering": ["text", "form_type", "id"],
                "indexes": [
                    models.Index(
                        fields=["text", "form_type"], name="writing_text_type_idx"
                    ),
                    models.Index(
                        fields=["normalized_text"], name="writing_normalized_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntryWriting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("primary", "主写法"),
                            ("alternate", "其他写法"),
                            ("disputed", "争议写法"),
                        ],
                        default="alternate",
                        max_length=20,
                        verbose_name="关系",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "初稿"),
                            ("reviewed", "已整理"),
                            ("disputed", "有分歧"),
                            ("rejected", "不采用"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="是否为当前关系"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_entry_writings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_writings",
                        to="guantou.entry",
                        verbose_name="词条",
                    ),
                ),
                (
                    "writing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_writings",
                        to="guantou.writingform",
                        verbose_name="写法",
                    ),
                ),
            ],
            options={
                "verbose_name": "词条写法关系",
                "verbose_name_plural": "词条写法关系",
                "ordering": ["entry_id", "relation_type", "id"],
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="writings",
            field=models.ManyToManyField(
                blank=True,
                related_name="entries",
                through="guantou.EntryWriting",
                to="guantou.writingform",
                verbose_name="写法",
            ),
        ),
        migrations.CreateModel(
            name="CuratorGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lexical_curator", "词条整理员"),
                            ("regional_curator", "地区整理员"),
                        ],
                        max_length=24,
                        verbose_name="权限类型",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生效时间"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=guantou.models.curator_grant_default_expiry,
                        verbose_name="到期时间",
                    ),
                ),
                ("reason", models.TextField(verbose_name="授权理由")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="撤销时间"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="撤销理由"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "dialect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curator_grants",
                        to="guantou.dialect",
                        verbose_name="授权地区范围",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_curator_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授权人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curator_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="整理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "整理员授权",
                "verbose_name_plural": "整理员授权",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "role", "valid_until"],
                        name="curator_user_role_idx",
                    ),
                    models.Index(
                        fields=["dialect", "role", "valid_until"],
                        name="curator_dialect_role_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("dialect__isnull", True), ("role", "lexical_curator")
                            ),
                            models.Q(
                                ("dialect__isnull", False), ("role", "regional_curator")
                            ),
                            _connector="OR",
                        ),
                        name="curator_role_scope_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valid_until__gt", models.F("valid_from"))),
                        name="curator_dates_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True),
                            ("revoked_at__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="curator_revocation_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="entrysenseconcept",
            constraint=models.UniqueConstraint(
                fields=("sense", "concept", "relation_type"),
                name="unique_sense_concept_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrysense",
            constraint=models.UniqueConstraint(
                fields=("entry", "sense_number"), name="unique_entry_sense_number"
            ),
        ),
        migrations.AddIndex(
            model_name="pronunciationvariant",
            index=models.Index(
                fields=["dialect", "status"], name="pron_variant_dialect_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pronunciationvariant",
            index=models.Index(fields=["ipa"], name="pron_variant_ipa_idx"),
        ),
        migrations.AddConstraint(
            model_name="pronunciationvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ipa", ""), _negated=True),
                    models.Q(("base_romanization", ""), _negated=True),
                    models.Q(("surface_romanization", ""), _negated=True),
                    _connector="OR",
                ),
                name="pronunciation_variant_has_form",
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["usage_dialect", "status"], name="recording_dialect_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["visibility", "status"], name="recording_visible_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordingentrylink",
            index=models.Index(
                fields=["entry", "role", "status"], name="recording_link_entry_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingentrylink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("recording", "entry", "role"),
                name="unique_current_recording_entry_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingentrylink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True), ("role", "primary"), ("status", "accepted")
                ),
                fields=("recording",),
                name="unique_accepted_primary_per_recording",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelink",
            index=models.Index(
                fields=["evidence", "relation_type"], name="evidence_relation_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entry__isnull", False),
                        ("pronunciation_variant__isnull", True),
                        ("recording__isnull", True),
                        ("recording_entry_link__isnull", True),
                        ("sense__isnull", True),
                    ),
                    models.Q(
                        ("entry__isnull", True),
                        ("pronunciation_variant__isnull", True),
                        ("recording__isnull", True),
                        ("recording_entry_link__isnull", True),
                        ("sense__isnull", False),
                    ),
                    models.Q(
                        ("entry__isnull", True),
                        ("pronunciation_variant__isnull", False),
                        ("recording__isnull", True),
                        ("recording_entry_link__isnull", True),
                        ("sense__isnull", True),
                    ),
                    models.Q(
                        ("entry__isnull", True),
                        ("pronunciation_variant__isnull", True),
                        ("recording__isnull", False),
                        ("recording_entry_link__isnull", True),
                        ("sense__isnull", True),
                    ),
                    models.Q(
                        ("entry__isnull", True),
                        ("pronunciation_variant__isnull", True),
                        ("recording__isnull", True),
                        ("recording_entry_link__isnull", False),
                        ("sense__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="evidence_link_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="usageattestation",
            index=models.Index(
                fields=["entry", "dialect", "active"], name="usage_entry_dialect_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usageattestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("attester__isnull", False)),
                fields=("attester", "entry", "dialect"),
                name="unique_active_usage_attestation",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrywriting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("entry", "writing", "relation_type"),
                name="unique_current_entry_writing",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrywriting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True),
                    ("relation_type", "primary"),
                    models.Q(("status", "rejected"), _negated=True),
                ),
                fields=("entry",),
                name="unique_current_primary_writing",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["status", "visibility"], name="entry_status_visible_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["usage_dialect", "status"], name="entry_dialect_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("canonical_entry__isnull", False), ("status", "redirected")
                    ),
                    models.Q(
                        models.Q(("status", "redirected"), _negated=True),
                        ("canonical_entry__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="entry_redirect_has_canonical",
            ),
        ),
    ]
