# Generated by Django 6.1 on 2026-09-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0020_entry_recording_v2_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyReviewCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(max_length=80, verbose_name="来源系统"),
                ),
                (
                    "candidate_key",
                    models.CharField(max_length=200, verbose_name="候选稳定键"),
                ),
                (
                    "candidate_type",
                    models.CharField(
                        choices=[
                            ("sense_segmentation", "建议分义"),
                            ("numbering_anomaly", "编号异常"),
                            ("pronunciation_variation", "读音差异复核"),
                            ("entry_split", "建议拆词条"),
                            ("possible_duplicate", "可能重复"),
                        ],
                        max_length=32,
                        verbose_name="候选类型",
                    ),
                ),
                (
                    "source_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="来源记录编号"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="候选原始材料"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(max_length=64, verbose_name="候选指纹"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("accepted", "已采纳"),
                            ("rejected", "不采纳"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "旧库审核候选",
                "verbose_name_plural": "旧库审核候选",
                "ordering": ["candidate_type", "candidate_key", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="legacyimportrecord",
            name="unique_legacy_import_source",
        ),
        migrations.AddConstraint(
            model_name="legacyimportrecord",
            constraint=models.UniqueConstraint(
                fields=("source_system", "source_table", "source_id", "target_model"),
                name="unique_legacy_import_target",
            ),
        ),
        migrations.AddField(
            model_name="legacyreviewcandidate",
            name="entries",
            field=models.ManyToManyField(
                blank=True,
                related_name="legacy_review_candidates",
                to="guantou.entry",
                verbose_name="相关词条",
            ),
        ),
        migrations.AddField(
            model_name="legacyreviewcandidate",
            name="primary_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_legacy_review_candidates",
                to="guantou.entry",
                verbose_name="主要词条",
            ),
        ),
        migrations.AddIndex(
            model_name="legacyreviewcandidate",
            index=models.Index(
                fields=["candidate_type", "status"], name="legacy_candidate_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyreviewcandidate",
            constraint=models.UniqueConstraint(
                fields=("source_system", "candidate_type", "candidate_key"),
                name="unique_legacy_review_candidate",
            ),
        ),
    ]
