# Generated by Django 6.1 on 2026-09-04 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0021_v2_legacy_import_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurationAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("review", "审核状态"),
                            ("split_entry", "拆分词条"),
                            ("merge_entries", "合并词条"),
                            ("narrow_scope", "缩小地区范围"),
                            ("link_concept", "关联概念"),
                            ("preserve_competing", "保留竞争解释"),
                            ("resolve_legacy", "处理旧库候选"),
                        ],
                        max_length=24,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("entry", "词条"),
                            ("sense", "义项"),
                            ("writing", "写法关系"),
                            ("pronunciation", "地区读音"),
                            ("recording", "录音"),
                            ("recording_link", "录音词条关系"),
                            ("legacy_candidate", "旧库候选"),
                        ],
                        max_length=24,
                        verbose_name="对象类型",
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField(verbose_name="对象编号")),
                (
                    "target_label",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="对象摘要"
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(default=dict, verbose_name="操作前快照"),
                ),
                (
                    "after_snapshot",
                    models.JSONField(default=dict, verbose_name="操作后快照"),
                ),
                ("reason", models.TextField(verbose_name="整理理由")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curation_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="整理人",
                    ),
                ),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="curation_actions",
                        to="guantou.evidencerecord",
                        verbose_name="依据",
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="guantou.curatorgrant",
                        verbose_name="使用的授权",
                    ),
                ),
            ],
            options={
                "verbose_name": "整理操作记录",
                "verbose_name_plural": "整理操作记录",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "created_at"],
                        name="curation_target_time_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="curation_actor_time_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CuratorApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lexical_curator", "词条整理员"),
                            ("regional_curator", "地区整理员"),
                        ],
                        max_length=24,
                        verbose_name="申请类型",
                    ),
                ),
                ("statement", models.TextField(verbose_name="申请说明")),
                ("experience", models.TextField(blank=True, verbose_name="相关经历")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "未通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(blank=True, verbose_name="审核理由"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curator_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "dialect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curator_applications",
                        to="guantou.dialect",
                        verbose_name="申请地区范围",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_curator_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "整理员申请",
                "verbose_name_plural": "整理员申请",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["applicant", "status", "created_at"],
                        name="curator_applicant_status_idx",
                    ),
                    models.Index(
                        fields=["role", "status", "created_at"],
                        name="curator_role_status_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("dialect__isnull", True), ("role", "lexical_curator")
                            ),
                            models.Q(
                                ("dialect__isnull", False), ("role", "regional_curator")
                            ),
                            _connector="OR",
                        ),
                        name="curator_application_scope_valid",
                    )
                ],
            },
        ),
    ]
