# Generated by Django 6.0.7 on 2026-09-06 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0024_collection_collectionentry_collectionrecording_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingcomment",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="guantou.entry",
            ),
        ),
        migrations.AlterField(
            model_name="recordingcomment",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="guantou.recording",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingcomment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("entry__isnull", True), ("recording__isnull", False)),
                    models.Q(("entry__isnull", False), ("recording__isnull", True)),
                    _connector="OR",
                ),
                name="discussion_exactly_one_target",
            ),
        ),
    ]
