# Generated by Django 5.0.3 on 2026-07-01 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近更新时间"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, verbose_name="摘要"),
                ),
                ("content", models.TextField(verbose_name="正文")),
                ("cover", models.URLField(blank=True, verbose_name="图片地址")),
                (
                    "visibility",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-update_time", "-id"],
            },
        ),
    ]
