# Generated by Django 6.0.7 on 2026-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_sitesettings_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="featured_cans",
            field=models.JSONField(blank=True, default=list, verbose_name="推荐罐头"),
        ),
    ]
