# Generated by Django 5.0.3 on 2026-07-01 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="user_info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "wechat",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="微信标识码"
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="qq标识码"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=100, verbose_name="昵称"),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, default="1970-1-1", verbose_name="生日"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=50, verbose_name="电话"),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        default="https://cos.edialect.top/website/默认头像.jpg",
                        verbose_name="头像",
                    ),
                ),
                (
                    "county",
                    models.CharField(blank=True, max_length=100, verbose_name="县区"),
                ),
                (
                    "town",
                    models.CharField(blank=True, max_length=100, verbose_name="乡镇"),
                ),
                ("points_sum", models.IntegerField(default=0, verbose_name="总积分")),
                ("points_now", models.IntegerField(default=0, verbose_name="当前积分")),
            ],
            options={
                "verbose_name": "用户详细信息",
                "verbose_name_plural": "用户详细信息",
            },
        ),
    ]
