from .models import ComponentType, ItemStatus, PrivilegeType


def free_theme(
    theme_id,
    name,
    desc,
    cover,
    accent,
    primary,
    ghost,
    effect,
    style_tag,
    dialect_tags=None,
):
    row = {
        "theme_id": theme_id,
        "name": name,
        "desc": desc,
        "cover_img": cover,
        "style_json": {
            "accent": accent,
            "primaryLook": primary,
            "ghostLook": ghost,
            "effect": effect,
        },
        "style_tags": [style_tag],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    }
    if dialect_tags:
        row["dialect_tags"] = dialect_tags
    return row


THEMES = [
    {
        "theme_id": "default",
        "name": "默认方言主题",
        "desc": "乡野松绿｜统一导航、按钮和卡片配色",
        "cover_img": "default",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fill",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "dialect_tags": [],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "paper",
        "name": "素白纸本",
        "desc": "田野笔记｜浅底细线、留白克制",
        "cover_img": "simple",
        "style_json": {
            "accent": "pine",
            "primaryLook": "outline",
            "ghostLook": "line",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "mistpad",
        "name": "雾青便笺",
        "desc": "浅雾便签｜软底清透",
        "cover_img": "simple",
        "style_json": {
            "accent": "mist",
            "primaryLook": "soft",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "member-pine",
        "name": "松风会员",
        "desc": "会员专属｜松绿细纹",
        "cover_img": "simple",
        "style_json": {"accent": "pine", "primaryLook": "fill"},
        "style_tags": ["简约"],
        "privilege_type": PrivilegeType.MEMBER,
        "get_condition": "开通会员后可启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-lantern",
        "name": "同乡灯会",
        "desc": "活动限定｜同乡灯火",
        "cover_img": "street",
        "style_json": {"accent": "clay", "effect": "none"},
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "限时同乡灯会产出",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "event-spring",
        "name": "开春乡音",
        "desc": "活动已结束｜已绝版",
        "cover_img": "festival",
        "style_json": {"accent": "clay"},
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.ACTIVITY,
        "get_condition": "活动已结束",
        "status": ItemStatus.DEPRECATED,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "creator-tile",
        "name": "方言达人青瓦",
        "desc": "创作者专属｜青瓦细纹",
        "cover_img": "guofeng",
        "style_json": {"accent": "pine"},
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.CREATOR,
        "get_condition": "完成方言创作任务后领取",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "chuankiang",
        "name": "川渝烟火",
        "desc": "巴蜀市井热辣风格",
        "cover_img": "dialect",
        "style_json": {"accent": "clay"},
        "style_tags": ["地域方言风"],
        "dialect_tags": ["川渝"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "敬请期待",
        "status": ItemStatus.COMING,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "wuyu",
        "name": "江南吴语",
        "desc": "水乡青墨｜浅波纹与雾青水洗",
        "cover_img": "simple",
        "style_json": {
            "accent": "mist",
            "primaryLook": "wash",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["江南吴语"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "yue",
        "name": "岭南粤韵",
        "desc": "骑楼朱印｜砖红满洲窗",
        "cover_img": "festival",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "glow",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["岭南粤韵"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "minnan",
        "name": "闽台闽南",
        "desc": "盐田暖金｜海岛桂色",
        "cover_img": "dialect",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "fill",
            "ghostLook": "fresh",
            "effect": "lift",
        },
        "style_tags": ["地域方言风"],
        "dialect_tags": ["闽台闽南"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "mimeograph",
        "name": "油印乡刊",
        "desc": "旧刊栏线｜茶褐油墨与纸边",
        "cover_img": "retro",
        "style_json": {
            "accent": "tea",
            "primaryLook": "classic",
            "ghostLook": "classic",
            "effect": "ink",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "teaslip",
        "name": "茶褐笺",
        "desc": "书房茶渍｜细线笺纸",
        "cover_img": "retro",
        "style_json": {
            "accent": "tea",
            "primaryLook": "outline",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "ledger",
        "name": "乡账旧册",
        "desc": "账册栏线｜陶土深沉",
        "cover_img": "retro",
        "style_json": {
            "accent": "clay",
            "primaryLook": "solemn",
            "ghostLook": "solemn",
            "effect": "none",
        },
        "style_tags": ["复古"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "nightferry",
        "name": "夜航电台",
        "desc": "夜航网格｜青墨指示灯",
        "cover_img": "cyber",
        "style_json": {
            "accent": "ink",
            "primaryLook": "contrast",
            "ghostLook": "gilt",
            "effect": "glow",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "signalbooth",
        "name": "讯号亭",
        "desc": "冷青指示灯｜赛博岗亭",
        "cover_img": "cyber",
        "style_json": {
            "accent": "mist",
            "primaryLook": "fill",
            "ghostLook": "filled",
            "effect": "pulse",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "gridlamp",
        "name": "网格航灯",
        "desc": "航灯散光｜金线网格",
        "cover_img": "cyber",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "bloom",
        },
        "style_tags": ["赛博"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "qingshan",
        "name": "青绿山水",
        "desc": "青绿层峦｜松绿描边留白",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "pine",
            "primaryLook": "outline",
            "ghostLook": "wash",
            "effect": "none",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "sealpaper",
        "name": "朱印宣纸",
        "desc": "朱印方章｜宣纸栏",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "glow",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "inkscroll",
        "name": "水墨长卷",
        "desc": "墨洗长卷｜晕墨留白",
        "cover_img": "guofeng",
        "style_json": {
            "accent": "ink",
            "primaryLook": "wash",
            "ghostLook": "wash",
            "effect": "ink",
        },
        "style_tags": ["国风"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "teahouse",
        "name": "茶馆木栏",
        "desc": "木栏茶座｜茶褐热络",
        "cover_img": "street",
        "style_json": {
            "accent": "tea",
            "primaryLook": "ardent",
            "ghostLook": "ardent",
            "effect": "lift",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "nightstall",
        "name": "夜市灯牌",
        "desc": "街沿灯火｜暖牌光晕",
        "cover_img": "street",
        "style_json": {
            "accent": "clay",
            "primaryLook": "fill",
            "ghostLook": "ardent",
            "effect": "glow",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "lanternalley",
        "name": "巷口灯笼",
        "desc": "灯笼散光｜桂金巷口",
        "cover_img": "street",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "soft",
            "ghostLook": "ardent",
            "effect": "bloom",
        },
        "style_tags": ["市井烟火"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "midautumn",
        "name": "中秋桂影",
        "desc": "桂金圆窗｜中秋听罐头",
        "cover_img": "festival",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "gilt",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "duanwu",
        "name": "端午蒲艾",
        "desc": "蒲艾青绿｜清新时节",
        "cover_img": "festival",
        "style_json": {
            "accent": "pine",
            "primaryLook": "fresh",
            "ghostLook": "fresh",
            "effect": "none",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "lanternyear",
        "name": "岁灯",
        "desc": "年节灯火｜朱印散光",
        "cover_img": "festival",
        "style_json": {
            "accent": "clay",
            "primaryLook": "seal",
            "ghostLook": "seal",
            "effect": "bloom",
        },
        "style_tags": ["节日限定"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "pixelbooth",
        "name": "像素广播亭",
        "desc": "像素格子｜清新播音亭",
        "cover_img": "anime",
        "style_json": {
            "accent": "mist",
            "primaryLook": "fresh",
            "ghostLook": "filled",
            "effect": "pulse",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "starglyph",
        "name": "星符乡音",
        "desc": "星符金边｜浅星点",
        "cover_img": "anime",
        "style_json": {
            "accent": "osmanthus",
            "primaryLook": "gilt",
            "ghostLook": "gilt",
            "effect": "glow",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "comicstrip",
        "name": "格子漫页",
        "desc": "漫画分格｜按压弹跳",
        "cover_img": "anime",
        "style_json": {
            "accent": "clay",
            "primaryLook": "fill",
            "ghostLook": "filled",
            "effect": "press",
        },
        "style_tags": ["二次元"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "inknight",
        "name": "墨夜极简",
        "desc": "深底细线｜极简暗色",
        "cover_img": "dark",
        "style_json": {
            "accent": "ink",
            "primaryLook": "solemn",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "voidgrid",
        "name": "空格暗网",
        "desc": "暗网细格｜雾青对比",
        "cover_img": "dark",
        "style_json": {
            "accent": "mist",
            "primaryLook": "contrast",
            "ghostLook": "quiet",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "theme_id": "coalnook",
        "name": "炭火暗角",
        "desc": "暖暗炭火｜薄雾茶褐",
        "cover_img": "dark",
        "style_json": {
            "accent": "tea",
            "primaryLook": "fog",
            "ghostLook": "fog",
            "effect": "none",
        },
        "style_tags": ["极简暗色"],
        "privilege_type": PrivilegeType.FREE,
        "get_condition": "免费启用",
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]

THEMES += [
    free_theme(
        "inkline",
        "青墨细栏",
        "青墨栏线｜细线克制",
        "simple",
        "ink",
        "outline",
        "line",
        "none",
        "简约",
    ),
    free_theme(
        "claypad",
        "陶土浅笺",
        "陶土便签｜浅底留白",
        "simple",
        "clay",
        "soft",
        "quiet",
        "none",
        "简约",
    ),
    free_theme(
        "teanote",
        "茶雾便条",
        "茶褐薄雾｜浅底便签",
        "simple",
        "tea",
        "soft",
        "fog",
        "none",
        "简约",
    ),
    free_theme(
        "fieldfresh",
        "田野清新",
        "松绿清透｜微微浮起",
        "simple",
        "pine",
        "fresh",
        "fresh",
        "lift",
        "简约",
    ),
    free_theme(
        "mistfill",
        "雾青实心",
        "雾青实键｜细线辅色",
        "simple",
        "mist",
        "fill",
        "line",
        "none",
        "简约",
    ),
    free_theme(
        "giltedge",
        "桂金细线",
        "桂金描边｜克制金边",
        "simple",
        "osmanthus",
        "outline",
        "gilt",
        "none",
        "简约",
    ),
    free_theme(
        "wuyubridge",
        "吴语石桥",
        "石桥苔痕｜浅底水洗",
        "simple",
        "mist",
        "soft",
        "wash",
        "none",
        "地域方言风",
        ["江南吴语"],
    ),
    free_theme(
        "wuyurain",
        "吴语夜雨",
        "夜雨晕墨｜青墨水洗",
        "simple",
        "ink",
        "wash",
        "fog",
        "ink",
        "地域方言风",
        ["江南吴语"],
    ),
    free_theme(
        "yueporch",
        "粤韵廊檐",
        "廊檐细线｜陶土印框",
        "festival",
        "clay",
        "outline",
        "seal",
        "none",
        "地域方言风",
        ["岭南粤韵"],
    ),
    free_theme(
        "yuewindow",
        "满洲金窗",
        "满洲窗金｜朱印浅光",
        "festival",
        "osmanthus",
        "seal",
        "gilt",
        "glow",
        "地域方言风",
        ["岭南粤韵"],
    ),
    free_theme(
        "minnanharbor",
        "闽南渡口",
        "渡口清透｜雾青实心",
        "dialect",
        "mist",
        "fill",
        "fresh",
        "none",
        "地域方言风",
        ["闽台闽南"],
    ),
    free_theme(
        "minnantemple",
        "闽南庙金",
        "庙宇金线｜陶土古风",
        "dialect",
        "clay",
        "classic",
        "seal",
        "gilt",
        "地域方言风",
        ["闽台闽南"],
    ),
    free_theme(
        "oldnews",
        "旧报栏",
        "旧报栏线｜青墨古风",
        "retro",
        "ink",
        "classic",
        "classic",
        "none",
        "复古",
    ),
    free_theme(
        "kilnslip",
        "窑褐笺",
        "窑褐细线｜深沉留白",
        "retro",
        "clay",
        "outline",
        "solemn",
        "none",
        "复古",
    ),
    free_theme(
        "teapress",
        "茶印旧刊",
        "茶褐实心｜按压旧刊",
        "retro",
        "tea",
        "fill",
        "classic",
        "press",
        "复古",
    ),
    free_theme(
        "rustwash",
        "锈迹水洗",
        "锈褐水洗｜晕墨旧痕",
        "retro",
        "tea",
        "wash",
        "quiet",
        "ink",
        "复古",
    ),
    free_theme(
        "ledgergold",
        "账册金线",
        "账册深沉｜桂金细框",
        "retro",
        "osmanthus",
        "solemn",
        "gilt",
        "none",
        "复古",
    ),
    free_theme(
        "mistclassic",
        "青灰旧栏",
        "青灰古风｜细线旧栏",
        "retro",
        "mist",
        "classic",
        "line",
        "none",
        "复古",
    ),
    free_theme(
        "nightgrid",
        "夜网岗",
        "夜网实心｜呼吸指示灯",
        "cyber",
        "ink",
        "fill",
        "quiet",
        "pulse",
        "赛博",
    ),
    free_theme(
        "coldlamp",
        "冷青航灯",
        "冷青描边｜航灯光晕",
        "cyber",
        "mist",
        "outline",
        "gilt",
        "glow",
        "赛博",
    ),
    free_theme(
        "coppernet",
        "铜网讯号",
        "铜网对比｜散光讯号",
        "cyber",
        "clay",
        "contrast",
        "filled",
        "bloom",
        "赛博",
    ),
    free_theme(
        "teaterminal",
        "茶褐终端",
        "茶褐对比｜呼吸终端",
        "cyber",
        "tea",
        "contrast",
        "quiet",
        "pulse",
        "赛博",
    ),
    free_theme(
        "goldwire",
        "金丝网格",
        "金丝描边｜金框网格",
        "cyber",
        "osmanthus",
        "outline",
        "gilt",
        "gilt",
        "赛博",
    ),
    free_theme(
        "voidpulse",
        "暗舱散光",
        "暗舱浅底｜散光指示",
        "cyber",
        "ink",
        "soft",
        "quiet",
        "bloom",
        "赛博",
    ),
    free_theme(
        "pinewash",
        "松绿泼墨",
        "松绿水洗｜晕墨层峦",
        "guofeng",
        "pine",
        "wash",
        "wash",
        "ink",
        "国风",
    ),
    free_theme(
        "inkseal",
        "青墨方印",
        "青墨朱印｜方印光晕",
        "guofeng",
        "ink",
        "seal",
        "seal",
        "glow",
        "国风",
    ),
    free_theme(
        "claywash",
        "陶土水墨",
        "陶土水洗｜素净留白",
        "guofeng",
        "clay",
        "wash",
        "quiet",
        "none",
        "国风",
    ),
    free_theme(
        "giltfan",
        "金扇细线",
        "金扇描边｜金框留白",
        "guofeng",
        "osmanthus",
        "classic",
        "gilt",
        "gilt",
        "国风",
    ),
    free_theme(
        "teascroll",
        "茶褐长卷",
        "茶褐水洗｜古风晕墨",
        "guofeng",
        "tea",
        "wash",
        "classic",
        "ink",
        "国风",
    ),
    free_theme(
        "mistshan",
        "远山淡墨",
        "远山描边｜淡墨留白",
        "guofeng",
        "mist",
        "outline",
        "wash",
        "none",
        "国风",
    ),
    free_theme(
        "stalltea",
        "茶摊灯火",
        "茶摊实心｜灯火光晕",
        "street",
        "tea",
        "fill",
        "ardent",
        "glow",
        "市井烟火",
    ),
    free_theme(
        "alleyink",
        "巷墨暖边",
        "巷墨热烈｜暖边微浮",
        "street",
        "ink",
        "ardent",
        "quiet",
        "lift",
        "市井烟火",
    ),
    free_theme(
        "bricklamp",
        "砖巷浅灯",
        "砖巷浅底｜暖边灯火",
        "street",
        "clay",
        "soft",
        "ardent",
        "none",
        "市井烟火",
    ),
    free_theme(
        "pinealley",
        "青瓦巷口",
        "青瓦热烈｜清新微浮",
        "street",
        "pine",
        "ardent",
        "fresh",
        "lift",
        "市井烟火",
    ),
    free_theme(
        "miststall",
        "雾夜摊牌",
        "雾夜实心｜薄雾灯火",
        "street",
        "mist",
        "fill",
        "fog",
        "glow",
        "市井烟火",
    ),
    free_theme(
        "goldstall",
        "金幌按压",
        "金幌热烈｜按压弹跳",
        "street",
        "osmanthus",
        "ardent",
        "gilt",
        "press",
        "市井烟火",
    ),
    free_theme(
        "springpine",
        "新岁松金",
        "新岁松绿｜金线清新",
        "festival",
        "pine",
        "gilt",
        "fresh",
        "gilt",
        "节日限定",
    ),
    free_theme(
        "teafest",
        "社戏茶印",
        "社戏茶褐｜朱印散光",
        "festival",
        "tea",
        "seal",
        "classic",
        "bloom",
        "节日限定",
    ),
    free_theme(
        "mistlantern",
        "纱灯雾金",
        "纱灯浅底｜雾金光晕",
        "festival",
        "mist",
        "soft",
        "gilt",
        "glow",
        "节日限定",
    ),
    free_theme(
        "inkyear",
        "岁墨朱印",
        "岁墨方印｜素净散光",
        "festival",
        "ink",
        "seal",
        "quiet",
        "bloom",
        "节日限定",
    ),
    free_theme(
        "clayfresh",
        "节庆陶土",
        "节庆陶土｜清新暖边",
        "festival",
        "clay",
        "fresh",
        "ardent",
        "none",
        "节日限定",
    ),
    free_theme(
        "osmanfill",
        "桂花实心",
        "桂花实键｜金框微浮",
        "festival",
        "osmanthus",
        "fill",
        "gilt",
        "lift",
        "节日限定",
    ),
    free_theme(
        "pixelfill",
        "像素实心",
        "像素实键｜细线按压",
        "anime",
        "mist",
        "fill",
        "line",
        "press",
        "二次元",
    ),
    free_theme(
        "starsoft",
        "星符浅底",
        "星符浅底｜金框呼吸",
        "anime",
        "osmanthus",
        "soft",
        "gilt",
        "pulse",
        "二次元",
    ),
    free_theme(
        "comicoutline",
        "漫页描边",
        "漫页细线｜浅填分格",
        "anime",
        "clay",
        "outline",
        "filled",
        "none",
        "二次元",
    ),
    free_theme(
        "inkpixel",
        "墨格广播",
        "墨格清新｜素净呼吸",
        "anime",
        "ink",
        "fresh",
        "quiet",
        "pulse",
        "二次元",
    ),
    free_theme(
        "teacomic",
        "茶褐漫格",
        "茶褐浅底｜古风按压",
        "anime",
        "tea",
        "soft",
        "classic",
        "press",
        "二次元",
    ),
    free_theme(
        "pineglyph",
        "青瓦星符",
        "青瓦金线｜清新光晕",
        "anime",
        "pine",
        "gilt",
        "fresh",
        "glow",
        "二次元",
    ),
    free_theme(
        "inkfill",
        "墨夜实心",
        "墨夜实键｜素净细线",
        "dark",
        "ink",
        "fill",
        "quiet",
        "none",
        "极简暗色",
    ),
    free_theme(
        "teacontrast",
        "炭火对比",
        "炭火墨色｜薄雾对比",
        "dark",
        "tea",
        "contrast",
        "fog",
        "none",
        "极简暗色",
    ),
    free_theme(
        "claydark",
        "暗窑深沉",
        "暗窑陶土｜深沉素净",
        "dark",
        "clay",
        "solemn",
        "quiet",
        "none",
        "极简暗色",
    ),
    free_theme(
        "osmandark",
        "暗金薄雾",
        "暗金雾面｜金框夜色",
        "dark",
        "osmanthus",
        "fog",
        "gilt",
        "none",
        "极简暗色",
    ),
    free_theme(
        "pinevoid",
        "夜田对比",
        "夜田松绿｜墨色对比",
        "dark",
        "pine",
        "contrast",
        "quiet",
        "none",
        "极简暗色",
    ),
    free_theme(
        "mistfog",
        "空雾暗角",
        "空雾雾面｜薄雾暗角",
        "dark",
        "mist",
        "fog",
        "fog",
        "none",
        "极简暗色",
    ),
    free_theme(
        "templefair",
        "庙会灯幡",
        "庙会灯幡｜陶土热烈",
        "folk",
        "clay",
        "ardent",
        "gilt",
        "glow",
        "节日风俗",
    ),
    free_theme(
        "paperhorse",
        "纸马乡祀",
        "纸马乡祀｜茶褐古风",
        "folk",
        "tea",
        "classic",
        "classic",
        "ink",
        "节日风俗",
    ),
    free_theme(
        "drumlane",
        "社鼓巷口",
        "社鼓巷口｜松绿清新",
        "folk",
        "pine",
        "fill",
        "fresh",
        "lift",
        "节日风俗",
    ),
    free_theme(
        "riverlantern",
        "河灯夜渡",
        "河灯夜渡｜雾青水洗",
        "folk",
        "mist",
        "wash",
        "fog",
        "none",
        "节日风俗",
    ),
    free_theme(
        "wheatrite",
        "麦收祭田",
        "麦收祭田｜桂金朱印",
        "folk",
        "osmanthus",
        "gilt",
        "seal",
        "gilt",
        "节日风俗",
    ),
    free_theme(
        "kilnrite",
        "窑神香火",
        "窑神香火｜陶土深沉",
        "folk",
        "clay",
        "solemn",
        "quiet",
        "none",
        "节日风俗",
    ),
    free_theme(
        "boatbless",
        "开船祈风",
        "开船祈风｜青墨细线",
        "folk",
        "ink",
        "outline",
        "line",
        "none",
        "节日风俗",
    ),
    free_theme(
        "beamred",
        "上梁红绸",
        "上梁红绸｜茶褐朱印",
        "folk",
        "tea",
        "seal",
        "classic",
        "press",
        "节日风俗",
    ),
    free_theme(
        "nightwatch",
        "打更巷火",
        "打更巷火｜松绿对比",
        "folk",
        "pine",
        "contrast",
        "ardent",
        "bloom",
        "节日风俗",
    ),
    free_theme(
        "springthaw",
        "开春解冻",
        "开春解冻｜松绿清新",
        "season",
        "pine",
        "fresh",
        "wash",
        "none",
        "季节时令",
    ),
    free_theme(
        "summerlotus",
        "夏荷田塘",
        "夏荷田塘｜雾青浅底",
        "season",
        "mist",
        "soft",
        "fresh",
        "lift",
        "季节时令",
    ),
    free_theme(
        "autumngrain",
        "秋晒谷场",
        "秋晒谷场｜桂金古风",
        "season",
        "osmanthus",
        "classic",
        "gilt",
        "none",
        "季节时令",
    ),
    free_theme(
        "winterhearth",
        "冬夜炭火",
        "冬夜炭火｜茶褐薄雾",
        "season",
        "tea",
        "fog",
        "quiet",
        "none",
        "季节时令",
    ),
    free_theme(
        "rainstart",
        "清明雨丝",
        "清明雨丝｜青墨水洗",
        "season",
        "ink",
        "wash",
        "wash",
        "ink",
        "季节时令",
    ),
    free_theme(
        "grainrain",
        "谷雨茶芽",
        "谷雨茶芽｜松绿实心",
        "season",
        "pine",
        "fill",
        "fog",
        "none",
        "季节时令",
    ),
    free_theme(
        "heatwave",
        "大暑蝉鸣",
        "大暑蝉鸣｜陶土热烈",
        "season",
        "clay",
        "ardent",
        "fresh",
        "glow",
        "季节时令",
    ),
    free_theme(
        "frostfall",
        "霜降薄雾",
        "霜降薄雾｜雾青细线",
        "season",
        "mist",
        "outline",
        "fog",
        "none",
        "季节时令",
    ),
    free_theme(
        "snownook",
        "小雪窗格",
        "小雪窗格｜青墨深沉",
        "season",
        "ink",
        "solemn",
        "gilt",
        "none",
        "季节时令",
    ),
]


DECORATIONS = [
    {
        "decoration_id": "cards-plain",
        "name": "系统默认罐头卡",
        "desc": "罐头卡片跟随当前主题。",
        "cover_img": "cards",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-plain",
        "name": "系统默认主页底",
        "desc": "个人主页背景跟随当前主题。",
        "cover_img": "profile",
        "style_json": {"background": "var(--page-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-plain",
        "name": "系统默认头像框",
        "desc": "头像不加额外边框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "0px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-bubble-plain",
        "name": "系统默认评论气泡",
        "desc": "评论气泡跟随当前主题。",
        "cover_img": "comment",
        "style_json": {"borderRadius": "12px"},
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-paper",
        "name": "宣纸折边",
        "desc": "罐头卡片带宣纸折边和浅阴影。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "4px",
            "borderColor": "var(--border-color)",
            "shadow": "0 8rpx 20rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-mist",
        "name": "江雾纹理",
        "desc": "个人中心底换成一层淡雾。",
        "cover_img": "profile",
        "style_json": {"background": "var(--surface-subtle-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-frame",
        "name": "青瓦圆框",
        "desc": "头像外加一圈主题色青瓦框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-paper",
        "name": "宣纸气泡",
        "desc": "评论气泡像一小张宣纸。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "4px",
            "background": "var(--surface-color)",
            "borderColor": "var(--border-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-brick",
        "name": "红砖压纹",
        "desc": "罐头卡片底带浅砖纹和陶土细边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "2px",
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-round",
        "name": "软圆罐头卡",
        "desc": "罐头卡片收成更圆的软边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "24px",
            "shadow": "0 12rpx 24rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-night",
        "name": "夜航网格",
        "desc": "个人中心底换成夜航网格。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-grain",
        "name": "田野浅纹",
        "desc": "个人中心底带一层浅田野纹。",
        "cover_img": "profile",
        "style_json": {"background": "var(--accent-subtle-color)"},
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-glyph",
        "name": "方言文字框",
        "desc": "头像框带一圈方言字。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "color": "var(--accent-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-ink",
        "name": "青墨细框",
        "desc": "头像外加一圈青墨细线。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "6px",
            "borderColor": "var(--text-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-round",
        "name": "软圆气泡",
        "desc": "评论气泡收成更圆的软边。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "24px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-ink",
        "name": "青墨方泡",
        "desc": "评论气泡换成青墨细方框。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "0px",
            "borderColor": "var(--text-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "navbar-plain",
        "name": "系统默认顶栏",
        "desc": "导航栏跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "nav",
        "style_json": {"color": "var(--text-color)"},
        "component_type": ComponentType.NAV_BAR,
        "group": "navbar",
        "style_tags": ["导航栏"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "tabbar-plain",
        "name": "系统默认底栏",
        "desc": "底部 Tab 跟随当前主题。小程序原生栏无法自定义。",
        "cover_img": "tabbar",
        "style_json": {
            "tabBackground": "var(--surface-color)",
            "tabColor": "var(--muted-color)",
            "tabAccent": "var(--accent-color)",
            "tabOnAccent": "var(--on-accent-color)",
            "tabEmphasis": "var(--text-color)",
            "tabBorder": "var(--border-color)",
        },
        "component_type": ComponentType.TAB_BAR,
        "group": "tabbar",
        "style_tags": ["底部Tab"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5"],
    },
    {
        "decoration_id": "cards-member",
        "name": "会员宣纸卡",
        "desc": "会员专属罐头卡片纹理。",
        "cover_img": "cards",
        "style_json": {"borderColor": "var(--accent-color)"},
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.MEMBER,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-creator",
        "name": "方言达人头像框",
        "desc": "完成创作任务后领取。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "4px"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.CREATOR,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-sharp",
        "name": "方折罐头卡",
        "desc": "罐头卡片收成直角折边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "0px",
            "borderWidth": "1px",
            "borderColor": "var(--text-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-wide",
        "name": "宽影罐头卡",
        "desc": "罐头卡片带更宽的浅阴影。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "16px",
            "shadow": "0 16rpx 32rpx var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-thin",
        "name": "细边罐头卡",
        "desc": "罐头卡片只留一圈细边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "8px",
            "borderWidth": "1px",
            "borderColor": "var(--border-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-accent",
        "name": "浅彩罐头卡",
        "desc": "罐头卡片底换成浅强调色。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "12px",
            "background": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-soft",
        "name": "雾底罐头卡",
        "desc": "罐头卡片底换成更软的浅底。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "20px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-ridge",
        "name": "压线罐头卡",
        "desc": "罐头卡片外加一圈加厚压线。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "6px",
            "borderWidth": "3px",
            "borderColor": "var(--accent-color)",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-wash",
        "name": "水墨浅底",
        "desc": "个人中心底换成一层水墨浅色。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--page-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-line",
        "name": "栏线主页",
        "desc": "个人中心底带一圈浅栏线。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "borderColor": "var(--border-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-deep",
        "name": "深雾主页",
        "desc": "个人中心底换成更深一层淡雾。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-subtle-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-glow",
        "name": "浅彩主页",
        "desc": "个人中心底换成浅强调色。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--accent-subtle-color)",
            "color": "var(--accent-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-fog",
        "name": "薄雾主页",
        "desc": "个人中心底换成更淡的页面底。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--page-color)",
            "color": "var(--muted-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-tile",
        "name": "青瓦主页",
        "desc": "个人中心底带一层青瓦浅纹。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--surface-color)",
            "borderColor": "var(--accent-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-thin",
        "name": "细线圆框",
        "desc": "头像外加一圈极细主题色。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "1px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-soft",
        "name": "浅彩宽框",
        "desc": "头像外加一圈更宽的浅彩框。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "8px",
            "borderColor": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-ridge",
        "name": "压线圆框",
        "desc": "头像外加一圈中等压线。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "3px", "borderColor": "var(--accent-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-mist",
        "name": "雾边圆框",
        "desc": "头像外加一圈浅雾边。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "2px", "borderColor": "var(--border-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-seal",
        "name": "朱印圆框",
        "desc": "头像外加一圈朱印色细框。",
        "cover_img": "avatar",
        "style_json": {
            "borderWidth": "4px",
            "borderColor": "var(--accent-color)",
            "color": "var(--text-color)",
        },
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-wide",
        "name": "宽墨圆框",
        "desc": "头像外加一圈更宽的墨框。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "10px", "borderColor": "var(--text-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-pill",
        "name": "胶囊气泡",
        "desc": "评论气泡收成更长的胶囊。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "32px",
            "background": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-soft",
        "name": "浅底气泡",
        "desc": "评论气泡换成更软的浅底。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "16px",
            "background": "var(--surface-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-line",
        "name": "细线气泡",
        "desc": "评论气泡只留一圈细线。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "8px",
            "borderColor": "var(--border-color)",
            "background": "transparent",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-accent",
        "name": "浅彩气泡",
        "desc": "评论气泡底换成浅强调色。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "12px",
            "background": "var(--accent-subtle-color)",
            "borderColor": "var(--accent-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-square",
        "name": "小方气泡",
        "desc": "评论气泡收成小圆角方框。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "2px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-fog",
        "name": "薄雾气泡",
        "desc": "评论气泡底换成一层薄雾。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "20px",
            "background": "var(--page-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-folk",
        "name": "社火折边",
        "desc": "罐头卡片带社火折边和暖边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "10px",
            "borderWidth": "2px",
            "borderColor": "var(--accent-color)",
            "background": "var(--accent-subtle-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "cards-season",
        "name": "时令浅卡",
        "desc": "罐头卡片换成时令浅底软边。",
        "cover_img": "cards",
        "style_json": {
            "borderRadius": "18px",
            "borderWidth": "0px",
            "background": "var(--page-color)",
        },
        "component_type": ComponentType.CARD,
        "group": "cards",
        "style_tags": ["罐头卡片"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-folk",
        "name": "庙会浅底",
        "desc": "个人中心底换成庙会浅暖色。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--accent-subtle-color)",
            "color": "var(--gilt-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "profile-season",
        "name": "四时浅底",
        "desc": "个人中心底换成四时浅底。",
        "cover_img": "profile",
        "style_json": {
            "background": "var(--page-color)",
            "color": "var(--text-secondary-color)",
        },
        "component_type": ComponentType.HOME_BG,
        "group": "profile",
        "style_tags": ["个人主页"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-folk",
        "name": "香火圆框",
        "desc": "头像外加一圈香火暖边。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "5px", "borderColor": "var(--gilt-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "avatar-season",
        "name": "节气细框",
        "desc": "头像外加一圈节气细边。",
        "cover_img": "avatar",
        "style_json": {"borderWidth": "3px", "borderColor": "var(--border-color)"},
        "component_type": ComponentType.AVATAR_FRAME,
        "group": "avatar",
        "style_tags": ["头像挂件"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-folk",
        "name": "社火气泡",
        "desc": "评论气泡带社火暖边。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "10px",
            "background": "var(--accent-subtle-color)",
            "borderColor": "var(--accent-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
    {
        "decoration_id": "comment-season",
        "name": "时令气泡",
        "desc": "评论气泡换成时令浅底。",
        "cover_img": "comment",
        "style_json": {
            "borderRadius": "22px",
            "background": "var(--surface-subtle-color)",
        },
        "component_type": ComponentType.COMMENT_BUBBLE,
        "group": "comment-bubble",
        "style_tags": ["评论区"],
        "privilege_type": PrivilegeType.FREE,
        "status": ItemStatus.AVAILABLE,
        "support_terminal": ["h5", "miniprogram"],
    },
]


_PACK_SURFACE_KEYS = {
    "radius": "cardBorderRadius",
    "card_bg": "cardBackground",
    "card_border": "cardBorderColor",
    "card_width": "cardBorderWidth",
    "card_shadow": "cardShadow",
    "card_pad": "cardPadding",
    "profile_bg": "profileBackground",
    "profile_color": "profileColor",
    "avatar_width": "avatarBorderWidth",
    "avatar_color": "avatarBorderColor",
    "comment_radius": "commentBorderRadius",
    "comment_bg": "commentBackground",
    "comment_border": "commentBorderColor",
    "comment_width": "commentBorderWidth",
    "nav_bg": "navBackground",
    "nav_color": "navColor",
    "nav_border": "navBorder",
    "tab_bg": "tabBackground",
    "tab_color": "tabColor",
    "tab_accent": "tabAccent",
    "tab_on_accent": "tabOnAccent",
    "tab_emphasis": "tabEmphasis",
    "tab_border": "tabBorder",
    "grain": "grainOpacity",
    "grain_image": "grainImage",
    "grain_size": "grainSize",
    "input_bg": "inputBackground",
    "input_radius": "inputBorderRadius",
    "input_border": "inputBorderColor",
    "input_width": "inputBorderWidth",
    "topic_bg": "topicBackground",
    "topic_radius": "topicBorderRadius",
    "topic_border": "topicBorderColor",
    "topic_width": "topicBorderWidth",
    "button_radius": "buttonRadius",
    "letter": "letterSpacing",
}

GRAIN_KINDS = {
    "dot": ("var(--grain-dot)", "46rpx 46rpx"),
    "paper": ("var(--grain-paper)", "14rpx 14rpx"),
    "fiber": ("var(--grain-fiber)", "18rpx 18rpx"),
    "grid": ("var(--grain-grid)", "24rpx 24rpx"),
    "rain": ("var(--grain-rain)", "16rpx 16rpx"),
    "mist": ("var(--grain-mist)", "32rpx 32rpx"),
    "seal": ("var(--grain-seal)", "36rpx 36rpx"),
    "glow": ("var(--grain-glow)", "28rpx 28rpx"),
    "ink": ("var(--grain-ink)", "22rpx 22rpx"),
}


def pack_surface(grain_kind=None, **kwargs):
    row = {}
    if grain_kind:
        image, size = GRAIN_KINDS[grain_kind]
        row["grainImage"] = image
        row["grainSize"] = size
    row.update(
        {
            _PACK_SURFACE_KEYS[key]: value
            for key, value in kwargs.items()
            if key in _PACK_SURFACE_KEYS
        }
    )
    return row


def style_family(**kwargs):
    row = {
        "cardBorderRadius": "12px",
        "cardBackground": "var(--surface-color)",
        "cardBorderColor": "var(--border-color)",
        "cardBorderWidth": "1px",
        "cardShadow": "none",
        "cardPadding": "24rpx",
        "profileBackground": "transparent",
        "profileColor": "var(--text-color)",
        "avatarBorderWidth": "2px",
        "avatarBorderColor": "var(--accent-color)",
        "commentBorderRadius": "12px",
        "commentBackground": "var(--surface-subtle-color)",
        "commentBorderColor": "transparent",
        "commentBorderWidth": "0px",
        "navBackground": "var(--accent-subtle-color)",
        "navColor": "var(--text-color)",
        "navBorder": "var(--accent-color)",
        "tabBackground": "var(--immersive-veil-color)",
        "tabColor": "var(--on-immersive-muted-color)",
        "tabAccent": "var(--immersive-accent-color)",
        "tabOnAccent": "var(--immersive-bg-strong-color)",
        "tabEmphasis": "var(--on-immersive-color)",
        "tabBorder": "var(--immersive-border-color)",
        "grainOpacity": "0.14",
        "grainImage": "var(--grain-dot)",
        "grainSize": "46rpx 46rpx",
        "inputBackground": "var(--surface-color)",
        "inputBorderRadius": "12px",
        "inputBorderColor": "var(--border-color)",
        "inputBorderWidth": "1px",
        "topicBackground": "var(--surface-subtle-color)",
        "topicBorderRadius": "12px",
        "topicBorderColor": "var(--border-color)",
        "topicBorderWidth": "1px",
        "buttonRadius": "999rpx",
        "letterSpacing": "0em",
    }
    row.update(pack_surface(**kwargs))
    return row


STYLE_FAMILIES = {
    "简约": style_family(
        radius="12px",
        card_width="1px",
        grain="0.1",
        grain_kind="dot",
        letter="0em",
        button_radius="14px",
        comment_width="0px",
        input_radius="12px",
        topic_radius="12px",
        card_pad="24rpx",
    ),
    "地域方言风": style_family(
        radius="14px",
        card_bg="var(--page-color)",
        card_width="0px",
        comment_radius="16px",
        avatar_width="0px",
        grain="0.16",
        grain_kind="mist",
        letter="0.02em",
        button_radius="16px",
        nav_bg="var(--page-color)",
        input_bg="var(--page-color)",
        input_width="0px",
        topic_bg="var(--page-color)",
        topic_width="0px",
        card_pad="28rpx",
    ),
    "复古": style_family(
        radius="2px",
        card_width="1px",
        card_border="var(--text-color)",
        comment_radius="2px",
        avatar_width="1px",
        grain="0.18",
        grain_kind="paper",
        letter="0.08em",
        button_radius="2px",
        comment_width="1px",
        comment_border="var(--text-color)",
        nav_bg="var(--page-color)",
        nav_border="var(--text-color)",
        input_radius="2px",
        input_border="var(--text-color)",
        topic_radius="2px",
        topic_border="var(--text-color)",
        card_pad="20rpx",
    ),
    "赛博": style_family(
        radius="0px",
        card_width="1px",
        card_border="var(--accent-color)",
        card_shadow="0 0 22rpx var(--accent-subtle-color)",
        comment_radius="0px",
        grain="0.2",
        grain_kind="grid",
        letter="0.1em",
        button_radius="0px",
        comment_width="1px",
        comment_border="var(--accent-color)",
        nav_bg="var(--page-color)",
        tab_bg="var(--page-color)",
        tab_color="var(--muted-color)",
        tab_accent="var(--accent-color)",
        tab_on_accent="var(--on-accent-color)",
        tab_emphasis="var(--text-color)",
        tab_border="var(--border-color)",
        input_radius="0px",
        input_border="var(--accent-color)",
        topic_radius="0px",
        topic_border="var(--accent-color)",
        card_pad="18rpx",
    ),
    "国风": style_family(
        radius="8px",
        card_width="2px",
        card_border="var(--gilt-color)",
        comment_radius="6px",
        avatar_width="3px",
        avatar_color="var(--gilt-color)",
        grain="0.12",
        grain_kind="seal",
        letter="0.14em",
        button_radius="8px",
        comment_width="1px",
        comment_border="var(--gilt-color)",
        nav_border="var(--gilt-color)",
        input_border="var(--gilt-color)",
        topic_border="var(--gilt-color)",
        card_pad="22rpx",
    ),
    "市井烟火": style_family(
        radius="10px",
        card_shadow="0 10rpx 24rpx var(--border-color)",
        comment_radius="10px",
        grain="0.14",
        grain_kind="fiber",
        letter="0.04em",
        button_radius="10px",
        nav_bg="var(--accent-subtle-color)",
        input_bg="var(--surface-subtle-color)",
        topic_bg="var(--accent-subtle-color)",
        card_pad="24rpx",
    ),
    "节日限定": style_family(
        radius="16px",
        card_border="var(--gilt-color)",
        card_shadow="0 0 18rpx var(--accent-subtle-color)",
        comment_radius="16px",
        avatar_color="var(--gilt-color)",
        grain="0.1",
        grain_kind="glow",
        letter="0.1em",
        button_radius="16px",
        comment_width="1px",
        comment_border="var(--gilt-color)",
        tab_bg="var(--accent-subtle-color)",
        tab_color="var(--muted-color)",
        tab_accent="var(--accent-color)",
        tab_on_accent="var(--on-accent-color)",
        tab_emphasis="var(--text-color)",
        tab_border="var(--border-color)",
        topic_border="var(--gilt-color)",
        card_pad="26rpx",
    ),
    "节日风俗": style_family(
        radius="12px",
        card_width="2px",
        card_border="var(--accent-color)",
        card_shadow="0 8rpx 20rpx var(--accent-subtle-color)",
        comment_radius="12px",
        grain="0.15",
        grain_kind="paper",
        letter="0.06em",
        button_radius="8px",
        comment_width="2px",
        comment_border="var(--accent-color)",
        input_width="2px",
        input_border="var(--accent-color)",
        topic_width="2px",
        topic_border="var(--accent-color)",
        card_pad="22rpx",
    ),
    "季节时令": style_family(
        radius="18px",
        card_bg="var(--page-color)",
        card_width="0px",
        comment_radius="18px",
        avatar_width="1px",
        grain="0.13",
        grain_kind="mist",
        letter="0.04em",
        button_radius="18px",
        input_bg="var(--page-color)",
        input_width="0px",
        topic_bg="var(--page-color)",
        topic_width="0px",
        card_pad="28rpx",
    ),
    "二次元": style_family(
        radius="6px",
        card_width="2px",
        card_border="var(--text-color)",
        comment_radius="8px",
        avatar_width="3px",
        grain="0.12",
        grain_kind="dot",
        grain_size="20rpx 20rpx",
        letter="0.08em",
        button_radius="8px",
        comment_width="2px",
        comment_border="var(--text-color)",
        input_width="2px",
        topic_width="2px",
        topic_border="var(--text-color)",
        card_pad="20rpx",
    ),
    "极简暗色": style_family(
        radius="8px",
        card_bg="var(--page-color)",
        card_width="1px",
        comment_radius="8px",
        grain="0.18",
        grain_kind="ink",
        letter="0.06em",
        button_radius="8px",
        comment_width="1px",
        comment_border="var(--border-color)",
        nav_bg="var(--page-color)",
        input_bg="var(--page-color)",
        topic_bg="var(--page-color)",
        card_pad="22rpx",
    ),
}


PACK_SURFACES = {
    "default": pack_surface(
        card_shadow="0 8rpx 22rpx var(--border-color)", grain="0.12"
    ),
    "paper": pack_surface(
        radius="4px",
        card_bg="var(--page-color)",
        comment_radius="4px",
        avatar_width="1px",
        grain="0.08",
    ),
    "mistpad": pack_surface(
        radius="16px",
        card_bg="var(--surface-subtle-color)",
        card_width="0px",
        comment_radius="16px",
        avatar_width="0px",
        grain="0.1",
    ),
    "inkline": pack_surface(
        radius="8px",
        card_width="1px",
        card_border="var(--text-color)",
        comment_radius="6px",
        comment_border="var(--border-color)",
        grain="0.09",
    ),
    "claypad": pack_surface(
        radius="14px", card_bg="var(--page-color)", comment_radius="14px", grain="0.11"
    ),
    "teanote": pack_surface(
        radius="12px",
        card_bg="var(--surface-subtle-color)",
        comment_bg="var(--page-color)",
        grain="0.13",
    ),
    "fieldfresh": pack_surface(
        radius="20px",
        card_shadow="0 12rpx 28rpx var(--border-color)",
        comment_radius="20px",
        grain="0.1",
    ),
    "mistfill": pack_surface(
        radius="12px",
        card_width="1px",
        comment_border="var(--border-color)",
        grain="0.12",
    ),
    "giltedge": pack_surface(
        radius="8px",
        card_border="var(--gilt-color)",
        comment_border="var(--gilt-color)",
        avatar_color="var(--gilt-color)",
        grain="0.09",
    ),
    "wuyu": pack_surface(
        radius="12px",
        card_bg="var(--page-color)",
        card_width="0px",
        comment_radius="14px",
        grain="0.15",
    ),
    "yue": pack_surface(
        radius="4px",
        card_width="3px",
        card_border="var(--accent-color)",
        comment_radius="4px",
        avatar_width="4px",
        grain="0.11",
    ),
    "minnan": pack_surface(
        radius="16px",
        card_border="var(--gilt-color)",
        card_shadow="0 10rpx 24rpx var(--border-color)",
        comment_radius="16px",
        grain="0.1",
    ),
    "wuyubridge": pack_surface(
        radius="14px",
        card_bg="var(--surface-subtle-color)",
        card_width="0px",
        grain="0.14",
    ),
    "wuyurain": pack_surface(
        radius="10px",
        card_bg="var(--page-color)",
        card_shadow="0 8rpx 20rpx var(--border-color)",
        grain="0.18",
    ),
    "yueporch": pack_surface(
        radius="6px",
        card_width="2px",
        card_border="var(--accent-color)",
        comment_radius="6px",
        grain="0.1",
    ),
    "yuewindow": pack_surface(
        radius="4px",
        card_border="var(--gilt-color)",
        card_width="2px",
        avatar_color="var(--gilt-color)",
        grain="0.09",
    ),
    "minnanharbor": pack_surface(
        radius="18px",
        card_shadow="0 10rpx 24rpx var(--border-color)",
        comment_radius="18px",
        grain="0.11",
    ),
    "minnantemple": pack_surface(
        radius="2px",
        card_width="2px",
        card_border="var(--gilt-color)",
        comment_radius="2px",
        grain="0.1",
    ),
    "mimeograph": pack_surface(
        radius="2px",
        card_width="1px",
        card_border="var(--text-color)",
        comment_radius="2px",
        grain="0.2",
    ),
    "teaslip": pack_surface(radius="8px", card_bg="var(--page-color)", grain="0.12"),
    "ledger": pack_surface(
        radius="0px",
        card_width="2px",
        card_border="var(--text-color)",
        comment_radius="0px",
        grain="0.16",
    ),
    "oldnews": pack_surface(
        radius="0px", card_width="1px", comment_radius="0px", grain="0.19"
    ),
    "kilnslip": pack_surface(radius="6px", card_bg="var(--page-color)", grain="0.13"),
    "teapress": pack_surface(
        radius="4px", card_width="2px", card_border="var(--accent-color)", grain="0.15"
    ),
    "rustwash": pack_surface(
        radius="10px", card_bg="var(--page-color)", card_width="0px", grain="0.17"
    ),
    "ledgergold": pack_surface(
        radius="0px", card_border="var(--gilt-color)", card_width="1px", grain="0.14"
    ),
    "mistclassic": pack_surface(radius="8px", card_width="1px", grain="0.12"),
    "nightferry": pack_surface(
        radius="6px",
        card_width="1px",
        card_border="var(--text-color)",
        card_shadow="0 0 24rpx var(--accent-subtle-color)",
        comment_radius="6px",
        grain="0.2",
    ),
    "signalbooth": pack_surface(
        radius="2px", card_width="2px", card_border="var(--accent-color)", grain="0.16"
    ),
    "gridlamp": pack_surface(
        radius="0px", card_width="1px", comment_radius="0px", grain="0.18"
    ),
    "nightgrid": pack_surface(
        radius="0px", card_width="1px", card_border="var(--accent-color)", grain="0.19"
    ),
    "coldlamp": pack_surface(
        radius="8px", card_shadow="0 0 20rpx var(--accent-subtle-color)", grain="0.14"
    ),
    "coppernet": pack_surface(radius="4px", card_width="2px", grain="0.15"),
    "teaterminal": pack_surface(
        radius="2px", card_width="1px", card_border="var(--text-color)", grain="0.17"
    ),
    "goldwire": pack_surface(
        radius="6px", card_border="var(--gilt-color)", grain="0.12"
    ),
    "voidpulse": pack_surface(
        radius="12px",
        card_bg="var(--page-color)",
        card_shadow="0 0 28rpx var(--accent-subtle-color)",
        grain="0.22",
    ),
    "qingshan": pack_surface(
        radius="10px", card_bg="var(--page-color)", card_width="0px", grain="0.11"
    ),
    "sealpaper": pack_surface(
        radius="4px", card_width="3px", card_border="var(--accent-color)", grain="0.1"
    ),
    "inkscroll": pack_surface(radius="8px", card_bg="var(--page-color)", grain="0.16"),
    "pinewash": pack_surface(
        radius="12px", card_bg="var(--page-color)", card_width="0px", grain="0.13"
    ),
    "inkseal": pack_surface(
        radius="2px",
        card_width="4px",
        card_border="var(--accent-color)",
        comment_radius="2px",
        grain="0.12",
    ),
    "claywash": pack_surface(
        radius="10px", card_bg="var(--surface-subtle-color)", grain="0.11"
    ),
    "giltfan": pack_surface(
        radius="8px", card_border="var(--gilt-color)", grain="0.09"
    ),
    "teascroll": pack_surface(radius="6px", card_bg="var(--page-color)", grain="0.14"),
    "mistshan": pack_surface(radius="16px", card_width="1px", grain="0.12"),
    "teahouse": pack_surface(
        radius="12px", card_shadow="0 10rpx 24rpx var(--border-color)", grain="0.13"
    ),
    "nightstall": pack_surface(
        radius="8px", card_width="1px", card_border="var(--accent-color)", grain="0.16"
    ),
    "lanternalley": pack_surface(
        radius="10px", card_shadow="0 0 18rpx var(--accent-subtle-color)", grain="0.14"
    ),
    "stalltea": pack_surface(
        radius="10px", card_bg="var(--accent-subtle-color)", grain="0.12"
    ),
    "alleyink": pack_surface(radius="6px", card_width="2px", grain="0.15"),
    "bricklamp": pack_surface(
        radius="4px", card_bg="var(--surface-subtle-color)", grain="0.13"
    ),
    "pinealley": pack_surface(
        radius="8px", card_shadow="0 8rpx 20rpx var(--border-color)", grain="0.12"
    ),
    "miststall": pack_surface(radius="14px", card_width="0px", grain="0.14"),
    "goldstall": pack_surface(
        radius="8px", card_border="var(--gilt-color)", grain="0.11"
    ),
    "midautumn": pack_surface(
        radius="16px", card_border="var(--gilt-color)", grain="0.1"
    ),
    "duanwu": pack_surface(
        radius="8px", card_width="2px", card_border="var(--accent-color)", grain="0.12"
    ),
    "lanternyear": pack_surface(
        radius="12px", card_shadow="0 0 20rpx var(--accent-subtle-color)", grain="0.13"
    ),
    "springpine": pack_surface(
        radius="14px", card_border="var(--gilt-color)", grain="0.1"
    ),
    "teafest": pack_surface(
        radius="6px", card_width="3px", card_border="var(--accent-color)", grain="0.11"
    ),
    "mistlantern": pack_surface(
        radius="18px", card_bg="var(--surface-subtle-color)", grain="0.12"
    ),
    "inkyear": pack_surface(radius="4px", card_width="3px", grain="0.14"),
    "clayfresh": pack_surface(
        radius="12px", card_shadow="0 8rpx 18rpx var(--border-color)", grain="0.11"
    ),
    "osmanfill": pack_surface(
        radius="10px", card_bg="var(--accent-subtle-color)", grain="0.09"
    ),
    "pixelbooth": pack_surface(
        radius="0px", card_width="2px", comment_radius="0px", grain="0.22"
    ),
    "starglyph": pack_surface(
        radius="20px",
        card_shadow="0 0 22rpx var(--accent-subtle-color)",
        comment_radius="20px",
        grain="0.12",
    ),
    "comicstrip": pack_surface(
        radius="2px",
        card_width="2px",
        card_border="var(--text-color)",
        comment_radius="2px",
        grain="0.1",
    ),
    "pixelfill": pack_surface(radius="0px", card_width="2px", grain="0.2"),
    "starsoft": pack_surface(
        radius="18px", card_bg="var(--surface-subtle-color)", grain="0.11"
    ),
    "comicoutline": pack_surface(
        radius="4px", card_width="2px", card_border="var(--text-color)", grain="0.1"
    ),
    "inkpixel": pack_surface(radius="0px", card_width="1px", grain="0.18"),
    "teacomic": pack_surface(radius="6px", card_bg="var(--page-color)", grain="0.12"),
    "pineglyph": pack_surface(
        radius="8px", card_border="var(--gilt-color)", grain="0.11"
    ),
    "inknight": pack_surface(
        radius="8px", card_width="1px", card_border="var(--text-color)", grain="0.2"
    ),
    "voidgrid": pack_surface(radius="0px", card_width="1px", grain="0.21"),
    "coalnook": pack_surface(
        radius="12px", card_bg="var(--surface-subtle-color)", grain="0.17"
    ),
    "inkfill": pack_surface(radius="8px", card_width="1px", grain="0.19"),
    "teacontrast": pack_surface(
        radius="6px", card_width="2px", card_border="var(--text-color)", grain="0.16"
    ),
    "claydark": pack_surface(radius="4px", card_bg="var(--page-color)", grain="0.18"),
    "osmandark": pack_surface(
        radius="10px", card_border="var(--gilt-color)", grain="0.15"
    ),
    "pinevoid": pack_surface(radius="2px", card_width="2px", grain="0.2"),
    "mistfog": pack_surface(
        radius="16px", card_bg="var(--page-color)", card_width="0px", grain="0.14"
    ),
    "templefair": pack_surface(radius="12px", card_width="2px", grain="0.15"),
    "paperhorse": pack_surface(radius="8px", card_bg="var(--page-color)", grain="0.17"),
    "drumlane": pack_surface(
        radius="14px", card_shadow="0 12rpx 24rpx var(--border-color)", grain="0.13"
    ),
    "riverlantern": pack_surface(radius="16px", card_width="0px", grain="0.16"),
    "wheatrite": pack_surface(
        card_border="var(--gilt-color)", avatar_color="var(--gilt-color)", grain="0.11"
    ),
    "kilnrite": pack_surface(radius="6px", card_bg="var(--page-color)", grain="0.18"),
    "boatbless": pack_surface(
        radius="4px", card_border="var(--text-color)", grain="0.14"
    ),
    "beamred": pack_surface(
        card_width="3px", card_border="var(--accent-color)", grain="0.12"
    ),
    "nightwatch": pack_surface(
        card_shadow="0 0 24rpx var(--accent-subtle-color)", grain="0.19"
    ),
    "springthaw": pack_surface(radius="20px", grain="0.11"),
    "summerlotus": pack_surface(
        radius="18px", card_bg="var(--surface-subtle-color)", grain="0.12"
    ),
    "autumngrain": pack_surface(
        radius="10px", card_border="var(--gilt-color)", grain="0.13"
    ),
    "winterhearth": pack_surface(
        radius="14px", card_bg="var(--page-color)", grain="0.17"
    ),
    "rainstart": pack_surface(card_width="0px", grain="0.18"),
    "grainrain": pack_surface(
        radius="16px", card_shadow="0 10rpx 22rpx var(--border-color)", grain="0.1"
    ),
    "heatwave": pack_surface(
        card_width="2px", card_border="var(--accent-color)", grain="0.14"
    ),
    "frostfall": pack_surface(radius="22px", card_width="0px", grain="0.15"),
    "snownook": pack_surface(
        radius="8px", card_width="1px", card_border="var(--text-color)", grain="0.16"
    ),
    "member-pine": pack_surface(
        radius="10px", card_width="2px", card_border="var(--accent-color)", grain="0.1"
    ),
    "event-lantern": pack_surface(
        radius="12px", card_shadow="0 0 20rpx var(--accent-subtle-color)", grain="0.13"
    ),
    "event-spring": pack_surface(
        radius="14px", card_border="var(--gilt-color)", grain="0.1"
    ),
    "creator-tile": pack_surface(radius="6px", card_width="2px", grain="0.11"),
}


PACK_GRAIN_KIND = {
    "paper": "paper",
    "mistpad": "mist",
    "inkline": "ink",
    "claypad": "fiber",
    "teanote": "paper",
    "fieldfresh": "mist",
    "mistfill": "mist",
    "giltedge": "seal",
    "wuyu": "mist",
    "wuyubridge": "mist",
    "wuyurain": "rain",
    "yue": "seal",
    "yueporch": "fiber",
    "yuewindow": "seal",
    "minnan": "seal",
    "minnanharbor": "mist",
    "minnantemple": "seal",
    "mimeograph": "paper",
    "teaslip": "paper",
    "ledger": "paper",
    "oldnews": "paper",
    "kilnslip": "fiber",
    "teapress": "paper",
    "rustwash": "fiber",
    "ledgergold": "seal",
    "mistclassic": "mist",
    "nightferry": "grid",
    "signalbooth": "grid",
    "gridlamp": "grid",
    "nightgrid": "grid",
    "coldlamp": "glow",
    "coppernet": "grid",
    "teaterminal": "grid",
    "goldwire": "seal",
    "voidpulse": "glow",
    "qingshan": "mist",
    "sealpaper": "seal",
    "inkscroll": "ink",
    "pinewash": "mist",
    "inkseal": "seal",
    "claywash": "fiber",
    "giltfan": "seal",
    "teascroll": "paper",
    "mistshan": "mist",
    "teahouse": "fiber",
    "nightstall": "glow",
    "lanternalley": "glow",
    "stalltea": "fiber",
    "alleyink": "ink",
    "bricklamp": "glow",
    "pinealley": "fiber",
    "miststall": "mist",
    "goldstall": "seal",
    "midautumn": "glow",
    "duanwu": "fiber",
    "lanternyear": "glow",
    "springpine": "seal",
    "teafest": "paper",
    "mistlantern": "mist",
    "inkyear": "ink",
    "clayfresh": "mist",
    "osmanfill": "seal",
    "pixelbooth": "grid",
    "starglyph": "glow",
    "comicstrip": "paper",
    "pixelfill": "grid",
    "starsoft": "mist",
    "comicoutline": "paper",
    "inkpixel": "grid",
    "teacomic": "paper",
    "pineglyph": "seal",
    "inknight": "ink",
    "voidgrid": "grid",
    "coalnook": "ink",
    "inkfill": "ink",
    "teacontrast": "ink",
    "claydark": "ink",
    "osmandark": "seal",
    "pinevoid": "grid",
    "mistfog": "mist",
    "templefair": "paper",
    "paperhorse": "paper",
    "drumlane": "fiber",
    "riverlantern": "glow",
    "wheatrite": "seal",
    "kilnrite": "fiber",
    "boatbless": "paper",
    "beamred": "fiber",
    "nightwatch": "glow",
    "springthaw": "mist",
    "summerlotus": "mist",
    "autumngrain": "seal",
    "winterhearth": "fiber",
    "rainstart": "rain",
    "grainrain": "rain",
    "heatwave": "glow",
    "frostfall": "mist",
    "snownook": "paper",
    "member-pine": "fiber",
    "event-lantern": "glow",
    "event-spring": "seal",
    "creator-tile": "paper",
}

PACK_FINISH = {
    "paper": pack_surface(
        letter="0.06em",
        comment_width="1px",
        comment_border="var(--border-color)",
        input_radius="4px",
        topic_radius="4px",
        nav_bg="var(--page-color)",
        button_radius="4px",
        card_pad="18rpx",
    ),
    "mistpad": pack_surface(
        letter="0.02em",
        input_width="0px",
        input_bg="var(--surface-subtle-color)",
        topic_width="0px",
        nav_bg="var(--surface-subtle-color)",
        button_radius="16px",
    ),
    "inkline": pack_surface(
        letter="0.06em",
        comment_width="1px",
        input_border="var(--text-color)",
        topic_border="var(--text-color)",
        nav_border="var(--text-color)",
        button_radius="8px",
    ),
    "giltedge": pack_surface(
        letter="0.12em",
        comment_width="1px",
        input_border="var(--gilt-color)",
        topic_border="var(--gilt-color)",
        nav_border="var(--gilt-color)",
        button_radius="8px",
    ),
    "yue": pack_surface(
        letter="0.08em",
        comment_width="2px",
        comment_border="var(--accent-color)",
        input_width="2px",
        input_border="var(--accent-color)",
        button_radius="4px",
    ),
    "wuyurain": pack_surface(
        letter="0.04em",
        input_bg="var(--page-color)",
        topic_bg="var(--page-color)",
        nav_bg="var(--page-color)",
    ),
    "nightferry": pack_surface(
        letter="0.12em",
        comment_width="1px",
        input_radius="0px",
        topic_radius="0px",
        button_radius="0px",
        nav_bg="var(--page-color)",
    ),
    "ledger": pack_surface(
        letter="0.1em",
        comment_width="2px",
        input_radius="0px",
        topic_radius="0px",
        button_radius="0px",
        card_pad="16rpx",
    ),
    "pixelbooth": pack_surface(
        letter="0.12em",
        comment_width="2px",
        input_radius="0px",
        topic_radius="0px",
        button_radius="0px",
        card_pad="16rpx",
    ),
    "midautumn": pack_surface(
        letter="0.12em",
        comment_width="1px",
        comment_border="var(--gilt-color)",
        input_border="var(--gilt-color)",
        topic_border="var(--gilt-color)",
        button_radius="16px",
    ),
    "springthaw": pack_surface(
        letter="0.03em",
        input_width="0px",
        topic_width="0px",
        button_radius="20px",
        card_pad="30rpx",
    ),
}

for _theme_id, _kind in PACK_GRAIN_KIND.items():
    PACK_SURFACES[_theme_id] = {
        **pack_surface(grain_kind=_kind),
        **PACK_SURFACES.get(_theme_id, {}),
    }
for _theme_id, _finish in PACK_FINISH.items():
    PACK_SURFACES[_theme_id] = {**PACK_SURFACES.get(_theme_id, {}), **_finish}


for _row in THEMES:
    tag = (_row.get("style_tags") or [None])[0]
    family = STYLE_FAMILIES.get(tag) or STYLE_FAMILIES["简约"]
    extra = PACK_SURFACES.get(_row["theme_id"]) or {}
    style = dict(_row.get("style_json") or {})
    style.update(family)
    style.update(extra)
    _row["style_json"] = style

DRESS_STYLE_BY_ID = {
    "cards-paper": "简约",
    "cards-brick": "地域方言风",
    "cards-round": "二次元",
    "cards-sharp": "赛博",
    "cards-wide": "市井烟火",
    "cards-thin": "极简暗色",
    "cards-accent": "节日限定",
    "cards-soft": "复古",
    "cards-ridge": "国风",
    "cards-folk": "节日风俗",
    "cards-season": "季节时令",
    "profile-mist": "地域方言风",
    "profile-night": "赛博",
    "profile-grain": "市井烟火",
    "profile-wash": "复古",
    "profile-line": "简约",
    "profile-deep": "极简暗色",
    "profile-glow": "节日限定",
    "profile-fog": "二次元",
    "profile-tile": "国风",
    "profile-folk": "节日风俗",
    "profile-season": "季节时令",
    "avatar-frame": "国风",
    "avatar-glyph": "二次元",
    "avatar-ink": "复古",
    "avatar-thin": "简约",
    "avatar-soft": "地域方言风",
    "avatar-ridge": "市井烟火",
    "avatar-mist": "极简暗色",
    "avatar-seal": "节日限定",
    "avatar-wide": "赛博",
    "avatar-folk": "节日风俗",
    "avatar-season": "季节时令",
    "comment-paper": "简约",
    "comment-round": "二次元",
    "comment-ink": "复古",
    "comment-pill": "市井烟火",
    "comment-soft": "地域方言风",
    "comment-line": "赛博",
    "comment-accent": "节日限定",
    "comment-square": "国风",
    "comment-fog": "极简暗色",
    "comment-folk": "节日风俗",
    "comment-season": "季节时令",
}

for _row in DECORATIONS:
    style_tag = DRESS_STYLE_BY_ID.get(_row["decoration_id"])
    if not style_tag:
        continue
    tags = list(_row.get("style_tags") or [])
    if style_tag not in tags:
        tags.append(style_tag)
    _row["style_tags"] = tags


def seed_catalog():
    from .models import CatalogVersion, DecorationItem, ThemeItem

    for row in THEMES:
        ThemeItem.objects.update_or_create(theme_id=row["theme_id"], defaults=row)
    for row in DECORATIONS:
        DecorationItem.objects.update_or_create(
            decoration_id=row["decoration_id"], defaults=row
        )
    CatalogVersion.objects.get_or_create(pk=1, defaults={"value": 1})
